INSERT INTO can_take_care VALUES ('jdaouze5k', 'cat');
INSERT INTO can_take_care VALUES ('jjeandon5l', 'rodent');
INSERT INTO can_take_care VALUES ('hpeirone5m', 'rabbit');
INSERT INTO can_take_care VALUES ('bkesper5n', 'rodent');
INSERT INTO can_take_care VALUES ('hhickford5o', 'rodent');
INSERT INTO can_take_care VALUES ('mkunath5p', 'cat');
INSERT INTO can_take_care VALUES ('fmctrustie5q', 'small dog');
INSERT INTO can_take_care VALUES ('whannigan5r', 'rodent');
INSERT INTO can_take_care VALUES ('ihannant5s', 'cat');
INSERT INTO can_take_care VALUES ('jcheshir5t', 'bird');
INSERT INTO can_take_care VALUES ('rkiggel5u', 'small dog');
INSERT INTO can_take_care VALUES ('bbreckell5v', 'big dog');
INSERT INTO can_take_care VALUES ('nkolodziejski5w', 'small dog');
INSERT INTO can_take_care VALUES ('agiacopello5x', 'bird');
INSERT INTO can_take_care VALUES ('rbaiden5y', 'bird');
INSERT INTO can_take_care VALUES ('cstaggs5z', 'cat');
INSERT INTO can_take_care VALUES ('jassante60', 'big dog');
INSERT INTO can_take_care VALUES ('bmalec61', 'rabbit');
INSERT INTO can_take_care VALUES ('bvarnals62', 'cat');
INSERT INTO can_take_care VALUES ('mrobken63', 'rabbit');
INSERT INTO can_take_care VALUES ('lmcmeekin64', 'bird');
INSERT INTO can_take_care VALUES ('mgreenshiels65', 'cat');
INSERT INTO can_take_care VALUES ('dandresen66', 'small dog');
INSERT INTO can_take_care VALUES ('agude67', 'cat');
INSERT INTO can_take_care VALUES ('hgeach68', 'rodent');
INSERT INTO can_take_care VALUES ('wdilger69', 'big dog');
INSERT INTO can_take_care VALUES ('gallsupp6a', 'rabbit');
INSERT INTO can_take_care VALUES ('zdenver6b', 'rabbit');
INSERT INTO can_take_care VALUES ('abroome6c', 'big dog');
INSERT INTO can_take_care VALUES ('wfathers6d', 'small dog');
INSERT INTO can_take_care VALUES ('tkhomishin6e', 'rodent');
INSERT INTO can_take_care VALUES ('kcardoso6f', 'bird');
INSERT INTO can_take_care VALUES ('lkennedy6g', 'big dog');
INSERT INTO can_take_care VALUES ('mvolante6h', 'cat');
INSERT INTO can_take_care VALUES ('swellbelove6i', 'rodent');
INSERT INTO can_take_care VALUES ('hannwyl6j', 'rabbit');
INSERT INTO can_take_care VALUES ('hwort6k', 'rabbit');
INSERT INTO can_take_care VALUES ('gworcs6l', 'small dog');
INSERT INTO can_take_care VALUES ('amc6m', 'small dog');
INSERT INTO can_take_care VALUES ('jdrennan6n', 'small dog');
INSERT INTO can_take_care VALUES ('djope6o', 'bird');
INSERT INTO can_take_care VALUES ('ccampanelle6p', 'bird');
INSERT INTO can_take_care VALUES ('dbugge6q', 'rabbit');
INSERT INTO can_take_care VALUES ('nmallinder6r', 'rabbit');
INSERT INTO can_take_care VALUES ('cle6s', 'bird');
INSERT INTO can_take_care VALUES ('ghaversham6t', 'rabbit');
INSERT INTO can_take_care VALUES ('lgoldes6u', 'cat');
INSERT INTO can_take_care VALUES ('dcockerill6v', 'big dog');
INSERT INTO can_take_care VALUES ('oshoorbrooke6w', 'rodent');
INSERT INTO can_take_care VALUES ('calthrop6x', 'small dog');
INSERT INTO can_take_care VALUES ('fgallard6y', 'rodent');
INSERT INTO can_take_care VALUES ('cmcenhill6z', 'rodent');
INSERT INTO can_take_care VALUES ('edanforth70', 'rabbit');
INSERT INTO can_take_care VALUES ('rsoutheran71', 'cat');
INSERT INTO can_take_care VALUES ('hmusto72', 'bird');
INSERT INTO can_take_care VALUES ('mbarrs73', 'rabbit');
INSERT INTO can_take_care VALUES ('tdrynan74', 'bird');
INSERT INTO can_take_care VALUES ('kbliss75', 'rabbit');
INSERT INTO can_take_care VALUES ('vclemence76', 'bird');
INSERT INTO can_take_care VALUES ('rmcsparran77', 'bird');
INSERT INTO can_take_care VALUES ('eandreu78', 'small dog');
INSERT INTO can_take_care VALUES ('dfound79', 'small dog');
INSERT INTO can_take_care VALUES ('uyeomans7a', 'small dog');
INSERT INTO can_take_care VALUES ('nspraging7b', 'bird');
INSERT INTO can_take_care VALUES ('cgiven7c', 'rabbit');
INSERT INTO can_take_care VALUES ('idalrymple7d', 'cat');
INSERT INTO can_take_care VALUES ('lhatter7e', 'rodent');
INSERT INTO can_take_care VALUES ('wkhomich7f', 'rodent');
INSERT INTO can_take_care VALUES ('cbrazier7g', 'rabbit');
INSERT INTO can_take_care VALUES ('vvooght7h', 'small dog');
INSERT INTO can_take_care VALUES ('csaunders7i', 'rodent');
INSERT INTO can_take_care VALUES ('eskpsey7j', 'small dog');
INSERT INTO can_take_care VALUES ('ndominicacci7k', 'cat');
INSERT INTO can_take_care VALUES ('cgaraway7l', 'rodent');
INSERT INTO can_take_care VALUES ('iduckerin7m', 'big dog');
INSERT INTO can_take_care VALUES ('tbowlesworth7n', 'cat');
INSERT INTO can_take_care VALUES ('cjudkins7o', 'bird');
INSERT INTO can_take_care VALUES ('tfayter7p', 'bird');
INSERT INTO can_take_care VALUES ('nlatey7q', 'cat');
INSERT INTO can_take_care VALUES ('lmcrinn7r', 'bird');
INSERT INTO can_take_care VALUES ('gsunman7s', 'cat');
INSERT INTO can_take_care VALUES ('arobertazzi7t', 'big dog');
INSERT INTO can_take_care VALUES ('skendell7u', 'rabbit');
INSERT INTO can_take_care VALUES ('sdoveston7v', 'big dog');
INSERT INTO can_take_care VALUES ('eewbanche7w', 'cat');
INSERT INTO can_take_care VALUES ('asole7x', 'rodent');
INSERT INTO can_take_care VALUES ('cfalco7y', 'rodent');
INSERT INTO can_take_care VALUES ('bkleinsinger7z', 'big dog');
INSERT INTO can_take_care VALUES ('ahudson80', 'bird');
INSERT INTO can_take_care VALUES ('lmcdonnell81', 'small dog');
INSERT INTO can_take_care VALUES ('kkrook82', 'cat');
INSERT INTO can_take_care VALUES ('brubens83', 'bird');
INSERT INTO can_take_care VALUES ('sledes84', 'small dog');
INSERT INTO can_take_care VALUES ('blyte85', 'cat');
INSERT INTO can_take_care VALUES ('kizakovitz86', 'cat');
INSERT INTO can_take_care VALUES ('mcatto87', 'rabbit');
INSERT INTO can_take_care VALUES ('kburnard88', 'bird');
INSERT INTO can_take_care VALUES ('emargaret89', 'small dog');
INSERT INTO can_take_care VALUES ('jgopsall8a', 'rabbit');
INSERT INTO can_take_care VALUES ('phentzeler8b', 'small dog');
INSERT INTO can_take_care VALUES ('eseares8c', 'rabbit');
INSERT INTO can_take_care VALUES ('hquin8d', 'rabbit');
INSERT INTO can_take_care VALUES ('clock8e', 'bird');
INSERT INTO can_take_care VALUES ('mtarry8f', 'cat');
INSERT INTO can_take_care VALUES ('hgulston8g', 'bird');
INSERT INTO can_take_care VALUES ('rtidder8h', 'small dog');
INSERT INTO can_take_care VALUES ('mtofano8i', 'rabbit');
INSERT INTO can_take_care VALUES ('lgiacomozzo8j', 'bird');
INSERT INTO can_take_care VALUES ('ogallacher8k', 'big dog');
INSERT INTO can_take_care VALUES ('nbletcher8l', 'small dog');
INSERT INTO can_take_care VALUES ('bandreuzzi8m', 'big dog');
INSERT INTO can_take_care VALUES ('btissington8n', 'rodent');
INSERT INTO can_take_care VALUES ('ecampana8o', 'rodent');
INSERT INTO can_take_care VALUES ('vculpan8p', 'cat');
INSERT INTO can_take_care VALUES ('rburtt8q', 'big dog');
INSERT INTO can_take_care VALUES ('dbendle8r', 'small dog');
INSERT INTO can_take_care VALUES ('wnegri8s', 'small dog');
INSERT INTO can_take_care VALUES ('golenchikov8t', 'bird');
INSERT INTO can_take_care VALUES ('gloftie8u', 'rabbit');
INSERT INTO can_take_care VALUES ('sledster8v', 'big dog');
INSERT INTO can_take_care VALUES ('emarvell8w', 'rabbit');
INSERT INTO can_take_care VALUES ('ntruscott8x', 'big dog');
INSERT INTO can_take_care VALUES ('lfrear8y', 'big dog');
INSERT INTO can_take_care VALUES ('wjameson8z', 'rodent');
INSERT INTO can_take_care VALUES ('nhambright90', 'cat');
INSERT INTO can_take_care VALUES ('sbegin91', 'small dog');
INSERT INTO can_take_care VALUES ('hwestphalen92', 'bird');
INSERT INTO can_take_care VALUES ('sind93', 'rabbit');
INSERT INTO can_take_care VALUES ('svondracek94', 'big dog');
INSERT INTO can_take_care VALUES ('gsambath95', 'rabbit');
INSERT INTO can_take_care VALUES ('dplunket96', 'rabbit');
INSERT INTO can_take_care VALUES ('vlaurent97', 'rabbit');
INSERT INTO can_take_care VALUES ('bcathenod98', 'cat');
INSERT INTO can_take_care VALUES ('sterbruggen99', 'big dog');
INSERT INTO can_take_care VALUES ('gmacgahy9a', 'big dog');
INSERT INTO can_take_care VALUES ('kverdie9b', 'cat');
INSERT INTO can_take_care VALUES ('ccrichmere9c', 'rabbit');
INSERT INTO can_take_care VALUES ('phurkett9d', 'rodent');
INSERT INTO can_take_care VALUES ('jmargett9e', 'small dog');
INSERT INTO can_take_care VALUES ('areynoldson9f', 'rabbit');
INSERT INTO can_take_care VALUES ('rroblett9g', 'big dog');
INSERT INTO can_take_care VALUES ('cspratling9h', 'bird');
INSERT INTO can_take_care VALUES ('eswires9i', 'rodent');
INSERT INTO can_take_care VALUES ('nblanchet9j', 'big dog');
INSERT INTO can_take_care VALUES ('lbaggett9k', 'small dog');
INSERT INTO can_take_care VALUES ('uespada9l', 'small dog');
INSERT INTO can_take_care VALUES ('jgrovier9m', 'rodent');
INSERT INTO can_take_care VALUES ('ajerrold9n', 'rodent');
INSERT INTO can_take_care VALUES ('mdenslow9o', 'small dog');
INSERT INTO can_take_care VALUES ('nbicksteth9p', 'cat');
INSERT INTO can_take_care VALUES ('ebalaizot9q', 'bird');
INSERT INTO can_take_care VALUES ('estener9r', 'rabbit');
INSERT INTO can_take_care VALUES ('uknights9s', 'rodent');
INSERT INTO can_take_care VALUES ('levelyn9t', 'rabbit');
INSERT INTO can_take_care VALUES ('aojeda9u', 'bird');
INSERT INTO can_take_care VALUES ('lpallesen9v', 'big dog');
INSERT INTO can_take_care VALUES ('kosgarby9w', 'big dog');
INSERT INTO can_take_care VALUES ('ngarrioch9x', 'rabbit');
INSERT INTO can_take_care VALUES ('pglisenan9y', 'small dog');
INSERT INTO can_take_care VALUES ('csigmund9z', 'small dog');
INSERT INTO can_take_care VALUES ('ftroppmanna0', 'rodent');
INSERT INTO can_take_care VALUES ('scraikera1', 'small dog');
INSERT INTO can_take_care VALUES ('bolomana2', 'rabbit');
INSERT INTO can_take_care VALUES ('rcharnleya3', 'cat');
INSERT INTO can_take_care VALUES ('kallansa4', 'small dog');
INSERT INTO can_take_care VALUES ('estevania5', 'cat');
INSERT INTO can_take_care VALUES ('acotgrovea6', 'big dog');
INSERT INTO can_take_care VALUES ('rchastona7', 'big dog');
INSERT INTO can_take_care VALUES ('apawsona8', 'cat');
INSERT INTO can_take_care VALUES ('ftouzeya9', 'small dog');
INSERT INTO can_take_care VALUES ('ethomsenaa', 'small dog');
INSERT INTO can_take_care VALUES ('wmalcherab', 'rodent');
INSERT INTO can_take_care VALUES ('rhanselmanac', 'bird');
INSERT INTO can_take_care VALUES ('idawidmanad', 'rabbit');
INSERT INTO can_take_care VALUES ('owalesbyae', 'bird');
INSERT INTO can_take_care VALUES ('cfanshawaf', 'bird');
INSERT INTO can_take_care VALUES ('bolderag', 'cat');
INSERT INTO can_take_care VALUES ('vdimitrovah', 'rodent');
INSERT INTO can_take_care VALUES ('twheatlandai', 'cat');
INSERT INTO can_take_care VALUES ('msandsallanaj', 'small dog');
INSERT INTO can_take_care VALUES ('bdaileyak', 'small dog');
INSERT INTO can_take_care VALUES ('lmarskellal', 'small dog');
INSERT INTO can_take_care VALUES ('rswanwickam', 'bird');
INSERT INTO can_take_care VALUES ('tbeaglesan', 'bird');
INSERT INTO can_take_care VALUES ('rgowlettao', 'small dog');
INSERT INTO can_take_care VALUES ('kkeamap', 'small dog');
INSERT INTO can_take_care VALUES ('wcoitaq', 'rabbit');
INSERT INTO can_take_care VALUES ('zkibbeyar', 'cat');
INSERT INTO can_take_care VALUES ('wcaneas', 'rabbit');
INSERT INTO can_take_care VALUES ('wmcmychemat', 'cat');
INSERT INTO can_take_care VALUES ('atwittyau', 'big dog');
INSERT INTO can_take_care VALUES ('hshurlockav', 'big dog');
INSERT INTO can_take_care VALUES ('acauleyaw', 'small dog');
INSERT INTO can_take_care VALUES ('mlosseljongax', 'rodent');
INSERT INTO can_take_care VALUES ('lgileay', 'big dog');
INSERT INTO can_take_care VALUES ('hhessentaleraz', 'big dog');
INSERT INTO can_take_care VALUES ('olivezeyb0', 'rabbit');
INSERT INTO can_take_care VALUES ('lgowanb1', 'cat');
INSERT INTO can_take_care VALUES ('ccosensb2', 'small dog');
INSERT INTO can_take_care VALUES ('gfaraganb3', 'bird');
INSERT INTO can_take_care VALUES ('rwillmoreb4', 'bird');
INSERT INTO can_take_care VALUES ('rcogganb5', 'small dog');
INSERT INTO can_take_care VALUES ('pdyhouseb6', 'small dog');
INSERT INTO can_take_care VALUES ('kpetkovb7', 'bird');
INSERT INTO can_take_care VALUES ('fwindramb8', 'rodent');
INSERT INTO can_take_care VALUES ('gsawtellb9', 'small dog');
INSERT INTO can_take_care VALUES ('cdodworthba', 'rodent');
INSERT INTO can_take_care VALUES ('groisbb', 'rodent');
INSERT INTO can_take_care VALUES ('owainbc', 'bird');
INSERT INTO can_take_care VALUES ('tcrucesbd', 'small dog');
INSERT INTO can_take_care VALUES ('dcroserbe', 'bird');
INSERT INTO can_take_care VALUES ('vtebbettbf', 'bird');
INSERT INTO can_take_care VALUES ('gerrowebg', 'bird');
INSERT INTO can_take_care VALUES ('tberranebh', 'bird');
INSERT INTO can_take_care VALUES ('ebarwackbi', 'big dog');
INSERT INTO can_take_care VALUES ('jsteagallbj', 'rabbit');
INSERT INTO can_take_care VALUES ('rpuckrinbk', 'rabbit');
INSERT INTO can_take_care VALUES ('vgarralsbl', 'bird');
INSERT INTO can_take_care VALUES ('amuzzlewhitebm', 'cat');
INSERT INTO can_take_care VALUES ('jzuponebn', 'bird');
INSERT INTO can_take_care VALUES ('lsmallridgebo', 'rodent');
INSERT INTO can_take_care VALUES ('ssoggeebp', 'small dog');
INSERT INTO can_take_care VALUES ('bsturebq', 'rabbit');
INSERT INTO can_take_care VALUES ('esouthernbr', 'rodent');
INSERT INTO can_take_care VALUES ('pkanwellbs', 'small dog');
INSERT INTO can_take_care VALUES ('ssancroftbt', 'small dog');
INSERT INTO can_take_care VALUES ('qchislettbu', 'big dog');
INSERT INTO can_take_care VALUES ('gloosmorebv', 'bird');
INSERT INTO can_take_care VALUES ('mmckeebw', 'rodent');
INSERT INTO can_take_care VALUES ('lstookebx', 'cat');
INSERT INTO can_take_care VALUES ('pandrzejczakby', 'bird');
INSERT INTO can_take_care VALUES ('jlidgelybz', 'small dog');
INSERT INTO can_take_care VALUES ('lsphinxec0', 'bird');
INSERT INTO can_take_care VALUES ('rcoopc1', 'bird');
INSERT INTO can_take_care VALUES ('edreppc2', 'rodent');
INSERT INTO can_take_care VALUES ('mizzattc3', 'bird');
INSERT INTO can_take_care VALUES ('edingc4', 'small dog');
INSERT INTO can_take_care VALUES ('gfrerec5', 'cat');
INSERT INTO can_take_care VALUES ('cortac6', 'rabbit');
INSERT INTO can_take_care VALUES ('flukianovichc7', 'small dog');
INSERT INTO can_take_care VALUES ('nsuscensc8', 'cat');
INSERT INTO can_take_care VALUES ('fpennc9', 'small dog');
INSERT INTO can_take_care VALUES ('sgummerca', 'rabbit');
INSERT INTO can_take_care VALUES ('bellincb', 'rabbit');
INSERT INTO can_take_care VALUES ('wdanbicc', 'big dog');
INSERT INTO can_take_care VALUES ('ameircd', 'bird');
INSERT INTO can_take_care VALUES ('apoggce', 'rabbit');
INSERT INTO can_take_care VALUES ('awombwellcf', 'big dog');
INSERT INTO can_take_care VALUES ('rnaisbetcg', 'rabbit');
INSERT INTO can_take_care VALUES ('mmulmuraych', 'rodent');
INSERT INTO can_take_care VALUES ('bknowlmanci', 'cat');
INSERT INTO can_take_care VALUES ('gbrotheridgecj', 'big dog');
INSERT INTO can_take_care VALUES ('zwashtellck', 'small dog');
INSERT INTO can_take_care VALUES ('dmussocl', 'cat');
INSERT INTO can_take_care VALUES ('klydallcm', 'cat');
INSERT INTO can_take_care VALUES ('clushercn', 'cat');
INSERT INTO can_take_care VALUES ('kmeachco', 'rodent');
INSERT INTO can_take_care VALUES ('nabbatecp', 'rabbit');
INSERT INTO can_take_care VALUES ('telphcq', 'small dog');
INSERT INTO can_take_care VALUES ('gwalmsleycr', 'big dog');
INSERT INTO can_take_care VALUES ('earundellcs', 'bird');
INSERT INTO can_take_care VALUES ('dnewcombect', 'cat');
INSERT INTO can_take_care VALUES ('rsweetencu', 'big dog');
INSERT INTO can_take_care VALUES ('hspreycv', 'small dog');
INSERT INTO can_take_care VALUES ('kvoiseycw', 'rodent');
INSERT INTO can_take_care VALUES ('rtenwickcx', 'small dog');
INSERT INTO can_take_care VALUES ('ivickermancy', 'cat');
INSERT INTO can_take_care VALUES ('lskeetecz', 'big dog');
INSERT INTO can_take_care VALUES ('egoldsond0', 'small dog');
INSERT INTO can_take_care VALUES ('jguidoned1', 'small dog');
INSERT INTO can_take_care VALUES ('aphillpottsd2', 'big dog');
INSERT INTO can_take_care VALUES ('hheigld3', 'small dog');
INSERT INTO can_take_care VALUES ('dbasshamd4', 'cat');
INSERT INTO can_take_care VALUES ('tbruted5', 'small dog');
INSERT INTO can_take_care VALUES ('mwitherdond6', 'rabbit');
INSERT INTO can_take_care VALUES ('cdemanched7', 'small dog');
INSERT INTO can_take_care VALUES ('nlangstoned8', 'bird');
INSERT INTO can_take_care VALUES ('jdarlassond9', 'rabbit');
INSERT INTO can_take_care VALUES ('skillikda', 'rodent');
INSERT INTO can_take_care VALUES ('fzolddb', 'bird');
INSERT INTO can_take_care VALUES ('amckeaveneydc', 'rodent');
INSERT INTO can_take_care VALUES ('blambledd', 'small dog');
INSERT INTO can_take_care VALUES ('hgeanyde', 'small dog');
INSERT INTO can_take_care VALUES ('lkenninghamdf', 'small dog');
INSERT INTO can_take_care VALUES ('dgaskendg', 'bird');
INSERT INTO can_take_care VALUES ('gstanwaydh', 'bird');
INSERT INTO can_take_care VALUES ('ndoegdi', 'small dog');
INSERT INTO can_take_care VALUES ('rtirkindj', 'rodent');
INSERT INTO can_take_care VALUES ('nlandmandk', 'rabbit');
INSERT INTO can_take_care VALUES ('aethridgedl', 'cat');
INSERT INTO can_take_care VALUES ('rseydlitzdm', 'cat');
INSERT INTO can_take_care VALUES ('jeldredgedn', 'big dog');
INSERT INTO can_take_care VALUES ('fdurransdo', 'cat');
INSERT INTO can_take_care VALUES ('hohartnettdp', 'cat');
INSERT INTO can_take_care VALUES ('ckobierskidq', 'rodent');
INSERT INTO can_take_care VALUES ('lrutherforthdr', 'rodent');
INSERT INTO can_take_care VALUES ('njeacopds', 'cat');
INSERT INTO can_take_care VALUES ('ibarrettdt', 'big dog');
INSERT INTO can_take_care VALUES ('smountdu', 'cat');
INSERT INTO can_take_care VALUES ('kaitchesondv', 'rabbit');
INSERT INTO can_take_care VALUES ('rhubbledw', 'big dog');
INSERT INTO can_take_care VALUES ('wfrederickdx', 'rodent');
INSERT INTO can_take_care VALUES ('goneilldy', 'bird');
INSERT INTO can_take_care VALUES ('bbrideauxdz', 'rodent');
INSERT INTO can_take_care VALUES ('lgooderhame0', 'small dog');
INSERT INTO can_take_care VALUES ('jemmanuele1', 'cat');
INSERT INTO can_take_care VALUES ('mreuvene2', 'cat');
INSERT INTO can_take_care VALUES ('fgallahere3', 'big dog');
INSERT INTO can_take_care VALUES ('cjosefe4', 'small dog');
INSERT INTO can_take_care VALUES ('mshiebere5', 'small dog');
INSERT INTO can_take_care VALUES ('lghidellie6', 'cat');
INSERT INTO can_take_care VALUES ('cmcquadee7', 'rodent');
INSERT INTO can_take_care VALUES ('gcrippene8', 'rabbit');
INSERT INTO can_take_care VALUES ('ipolleye9', 'rabbit');
INSERT INTO can_take_care VALUES ('rcollinetteea', 'small dog');
INSERT INTO can_take_care VALUES ('sforgieeb', 'rabbit');
INSERT INTO can_take_care VALUES ('dwillderec', 'rodent');
INSERT INTO can_take_care VALUES ('zantaoed', 'small dog');
INSERT INTO can_take_care VALUES ('jyewdaleee', 'small dog');
INSERT INTO can_take_care VALUES ('rrenforthef', 'cat');
INSERT INTO can_take_care VALUES ('enindeg', 'cat');
INSERT INTO can_take_care VALUES ('igertzeh', 'cat');
INSERT INTO can_take_care VALUES ('cdilkesei', 'big dog');
INSERT INTO can_take_care VALUES ('bpickoverej', 'bird');
INSERT INTO can_take_care VALUES ('hordek', 'cat');
INSERT INTO can_take_care VALUES ('espositoel', 'big dog');
INSERT INTO can_take_care VALUES ('cstilemanem', 'small dog');
INSERT INTO can_take_care VALUES ('spoleen', 'bird');
INSERT INTO can_take_care VALUES ('ptweedeo', 'rabbit');
INSERT INTO can_take_care VALUES ('cogbourneep', 'small dog');
INSERT INTO can_take_care VALUES ('vthandieq', 'bird');
INSERT INTO can_take_care VALUES ('mdominettier', 'big dog');
INSERT INTO can_take_care VALUES ('nscoltses', 'bird');
INSERT INTO can_take_care VALUES ('mhughesdonet', 'big dog');
INSERT INTO can_take_care VALUES ('zmartonfieu', 'cat');
INSERT INTO can_take_care VALUES ('cwhitlockev', 'big dog');
INSERT INTO can_take_care VALUES ('nstensonew', 'rabbit');
INSERT INTO can_take_care VALUES ('ctownendex', 'bird');
INSERT INTO can_take_care VALUES ('gdomeniconeey', 'small dog');
INSERT INTO can_take_care VALUES ('vlidgettez', 'big dog');
INSERT INTO can_take_care VALUES ('llarkcumf0', 'bird');
INSERT INTO can_take_care VALUES ('mgeraldof1', 'rodent');
INSERT INTO can_take_care VALUES ('bcharerf2', 'cat');
INSERT INTO can_take_care VALUES ('chewsonf3', 'rodent');
INSERT INTO can_take_care VALUES ('ckettsf4', 'bird');
INSERT INTO can_take_care VALUES ('adanzelmanf5', 'big dog');
INSERT INTO can_take_care VALUES ('fbrabonf6', 'cat');
INSERT INTO can_take_care VALUES ('vdavidovichf7', 'small dog');
INSERT INTO can_take_care VALUES ('vbarthodf8', 'cat');
INSERT INTO can_take_care VALUES ('abunkerf9', 'rabbit');
INSERT INTO can_take_care VALUES ('ibyfordfa', 'rodent');
INSERT INTO can_take_care VALUES ('rchristauffourfb', 'bird');
INSERT INTO can_take_care VALUES ('adelongfc', 'rodent');
INSERT INTO can_take_care VALUES ('rmalyjfd', 'cat');
INSERT INTO can_take_care VALUES ('bbuttsfe', 'rabbit');
INSERT INTO can_take_care VALUES ('ndoolyff', 'bird');
INSERT INTO can_take_care VALUES ('hniccolsfg', 'bird');
INSERT INTO can_take_care VALUES ('gocarranfh', 'rodent');
INSERT INTO can_take_care VALUES ('brodderfi', 'bird');
INSERT INTO can_take_care VALUES ('emongerfj', 'rabbit');
INSERT INTO can_take_care VALUES ('redgefk', 'cat');
INSERT INTO can_take_care VALUES ('cgeorgotfl', 'bird');
INSERT INTO can_take_care VALUES ('tspeddingfm', 'rabbit');
INSERT INTO can_take_care VALUES ('bpellerfn', 'small dog');
INSERT INTO can_take_care VALUES ('zheinekefo', 'bird');
INSERT INTO can_take_care VALUES ('thallowsfp', 'big dog');
INSERT INTO can_take_care VALUES ('tnazaretfq', 'cat');
INSERT INTO can_take_care VALUES ('sfitzgibbonfr', 'bird');
INSERT INTO can_take_care VALUES ('jpirazzifs', 'big dog');
INSERT INTO can_take_care VALUES ('kkerswillft', 'cat');
INSERT INTO can_take_care VALUES ('fabrahamowitczfu', 'bird');
INSERT INTO can_take_care VALUES ('dleekfv', 'bird');
INSERT INTO can_take_care VALUES ('pmaldenfw', 'rabbit');
INSERT INTO can_take_care VALUES ('kspykinsfx', 'rodent');
INSERT INTO can_take_care VALUES ('kmyallfy', 'big dog');
INSERT INTO can_take_care VALUES ('dfreeburyfz', 'rabbit');
INSERT INTO can_take_care VALUES ('gmacintoshg0', 'rabbit');
INSERT INTO can_take_care VALUES ('mrobertseng1', 'cat');
INSERT INTO can_take_care VALUES ('astanlockg2', 'small dog');
INSERT INTO can_take_care VALUES ('jedghinng3', 'cat');
INSERT INTO can_take_care VALUES ('fnillesg4', 'small dog');
INSERT INTO can_take_care VALUES ('alomaxg5', 'rabbit');
INSERT INTO can_take_care VALUES ('gbladong6', 'small dog');
INSERT INTO can_take_care VALUES ('adimbylowg7', 'bird');
INSERT INTO can_take_care VALUES ('rshepherdsong8', 'rabbit');
INSERT INTO can_take_care VALUES ('jlavertyg9', 'small dog');
INSERT INTO can_take_care VALUES ('ashemminga', 'rabbit');
INSERT INTO can_take_care VALUES ('ghickengb', 'big dog');
INSERT INTO can_take_care VALUES ('rbattellegc', 'small dog');
INSERT INTO can_take_care VALUES ('dhoneyghangd', 'cat');
INSERT INTO can_take_care VALUES ('rgutteridgege', 'cat');
INSERT INTO can_take_care VALUES ('rmoppettgf', 'rodent');
INSERT INTO can_take_care VALUES ('givannikovgg', 'small dog');
INSERT INTO can_take_care VALUES ('umccaheygh', 'rabbit');
INSERT INTO can_take_care VALUES ('lpaolozzigi', 'small dog');
INSERT INTO can_take_care VALUES ('ttullotgj', 'big dog');
INSERT INTO can_take_care VALUES ('cgarmstongk', 'rabbit');
INSERT INTO can_take_care VALUES ('lmaesgl', 'rodent');
INSERT INTO can_take_care VALUES ('dputtickgm', 'big dog');
INSERT INTO can_take_care VALUES ('rbimgn', 'small dog');
INSERT INTO can_take_care VALUES ('rpothergillgo', 'bird');
INSERT INTO can_take_care VALUES ('ecashleygp', 'small dog');
INSERT INTO can_take_care VALUES ('denterleingq', 'rabbit');
INSERT INTO can_take_care VALUES ('tpetrolgr', 'rabbit');
INSERT INTO can_take_care VALUES ('ldannellgs', 'big dog');
INSERT INTO can_take_care VALUES ('jcorteneygt', 'rabbit');
INSERT INTO can_take_care VALUES ('hracegu', 'bird');
INSERT INTO can_take_care VALUES ('dblabygv', 'small dog');
INSERT INTO can_take_care VALUES ('chagleygw', 'big dog');
INSERT INTO can_take_care VALUES ('dtyriegx', 'big dog');
INSERT INTO can_take_care VALUES ('aapplebygy', 'rodent');
INSERT INTO can_take_care VALUES ('tdigz', 'small dog');
INSERT INTO can_take_care VALUES ('hmcphelimeyh0', 'cat');
INSERT INTO can_take_care VALUES ('bgookh1', 'bird');
INSERT INTO can_take_care VALUES ('gmchaffyh2', 'big dog');
INSERT INTO can_take_care VALUES ('aclerkh3', 'cat');
INSERT INTO can_take_care VALUES ('pglanesterh4', 'big dog');
INSERT INTO can_take_care VALUES ('cbeazeyh5', 'cat');
INSERT INTO can_take_care VALUES ('fwalcherh6', 'small dog');
INSERT INTO can_take_care VALUES ('tdongallh7', 'rodent');
INSERT INTO can_take_care VALUES ('mbrisleyh8', 'rodent');
INSERT INTO can_take_care VALUES ('tzecchiih9', 'rodent');
INSERT INTO can_take_care VALUES ('jkerreyha', 'small dog');
INSERT INTO can_take_care VALUES ('fcobbinghb', 'rodent');
INSERT INTO can_take_care VALUES ('nantoshc', 'big dog');
INSERT INTO can_take_care VALUES ('crodriguezhd', 'rodent');
INSERT INTO can_take_care VALUES ('tgarbarhe', 'bird');
INSERT INTO can_take_care VALUES ('sdeehf', 'bird');
INSERT INTO can_take_care VALUES ('abodocshg', 'small dog');
INSERT INTO can_take_care VALUES ('lranbyhh', 'bird');
INSERT INTO can_take_care VALUES ('ddrillingcourthi', 'rodent');
INSERT INTO can_take_care VALUES ('mgatehj', 'small dog');
INSERT INTO can_take_care VALUES ('ledoweshk', 'small dog');
INSERT INTO can_take_care VALUES ('sguidottihl', 'rodent');
INSERT INTO can_take_care VALUES ('mcatthm', 'bird');
INSERT INTO can_take_care VALUES ('jjessonhn', 'bird');
INSERT INTO can_take_care VALUES ('cpattisonho', 'big dog');
INSERT INTO can_take_care VALUES ('rmcparlandhp', 'bird');
INSERT INTO can_take_care VALUES ('mklimushq', 'rabbit');
INSERT INTO can_take_care VALUES ('sopiehr', 'rabbit');
INSERT INTO can_take_care VALUES ('shuxhamhs', 'rabbit');
INSERT INTO can_take_care VALUES ('fhinrichht', 'rabbit');
INSERT INTO can_take_care VALUES ('dmacgeehu', 'rodent');
INSERT INTO can_take_care VALUES ('jlindbackhv', 'cat');
INSERT INTO can_take_care VALUES ('cgreguolihw', 'small dog');
INSERT INTO can_take_care VALUES ('gnimmohx', 'rodent');
INSERT INTO can_take_care VALUES ('ekilfoylehy', 'big dog');
INSERT INTO can_take_care VALUES ('rchazettehz', 'rabbit');
INSERT INTO can_take_care VALUES ('dbillami0', 'bird');
INSERT INTO can_take_care VALUES ('lmacurai1', 'bird');
INSERT INTO can_take_care VALUES ('dbremeni2', 'small dog');
INSERT INTO can_take_care VALUES ('ehintzeri3', 'small dog');
INSERT INTO can_take_care VALUES ('nbiancoi4', 'rabbit');
INSERT INTO can_take_care VALUES ('tkubeci5', 'bird');
INSERT INTO can_take_care VALUES ('alowingi6', 'rabbit');
INSERT INTO can_take_care VALUES ('gbeddardi7', 'rabbit');
INSERT INTO can_take_care VALUES ('rcolnetti8', 'bird');
INSERT INTO can_take_care VALUES ('sbanthorpei9', 'cat');
INSERT INTO can_take_care VALUES ('fanfussoia', 'rodent');
INSERT INTO can_take_care VALUES ('apurcellib', 'rodent');
INSERT INTO can_take_care VALUES ('mmawtusic', 'big dog');
INSERT INTO can_take_care VALUES ('nslowleyid', 'rabbit');
INSERT INTO can_take_care VALUES ('abeckenie', 'big dog');
INSERT INTO can_take_care VALUES ('maskewif', 'bird');
INSERT INTO can_take_care VALUES ('ebanfillig', 'big dog');
INSERT INTO can_take_care VALUES ('edumbellih', 'rodent');
INSERT INTO can_take_care VALUES ('ascoffinsii', 'big dog');
INSERT INTO can_take_care VALUES ('gbrafieldij', 'cat');
INSERT INTO can_take_care VALUES ('ringrahamik', 'rabbit');
INSERT INTO can_take_care VALUES ('bmuntonil', 'bird');
INSERT INTO can_take_care VALUES ('dbremeyerim', 'bird');
INSERT INTO can_take_care VALUES ('glangerin', 'small dog');
INSERT INTO can_take_care VALUES ('wgeramio', 'rabbit');
INSERT INTO can_take_care VALUES ('rwhittingtonip', 'rodent');
INSERT INTO can_take_care VALUES ('jbutterworthiq', 'big dog');
INSERT INTO can_take_care VALUES ('hchittockir', 'rodent');
INSERT INTO can_take_care VALUES ('abanvilleis', 'bird');
INSERT INTO can_take_care VALUES ('oskeldingeit', 'big dog');
INSERT INTO can_take_care VALUES ('lguerreruiu', 'rabbit');
INSERT INTO can_take_care VALUES ('clandisiv', 'rodent');
INSERT INTO can_take_care VALUES ('lmaccoughaniw', 'small dog');
INSERT INTO can_take_care VALUES ('plaurentix', 'big dog');
INSERT INTO can_take_care VALUES ('cdurbiniy', 'big dog');
INSERT INTO can_take_care VALUES ('abloyesiz', 'big dog');
INSERT INTO can_take_care VALUES ('coliviej0', 'rodent');
INSERT INTO can_take_care VALUES ('eblodgj1', 'rabbit');
INSERT INTO can_take_care VALUES ('rdunkerlyj2', 'big dog');
INSERT INTO can_take_care VALUES ('dhutcheonsj3', 'cat');
INSERT INTO can_take_care VALUES ('csalsbergj4', 'rabbit');
INSERT INTO can_take_care VALUES ('mparellj5', 'bird');
INSERT INTO can_take_care VALUES ('dstokerj6', 'small dog');
INSERT INTO can_take_care VALUES ('mmartinetj7', 'rabbit');
INSERT INTO can_take_care VALUES ('cbengerj8', 'bird');
INSERT INTO can_take_care VALUES ('iproshj9', 'big dog');
INSERT INTO can_take_care VALUES ('aallanbyja', 'rabbit');
INSERT INTO can_take_care VALUES ('nwydjb', 'big dog');
INSERT INTO can_take_care VALUES ('nvanjc', 'cat');
INSERT INTO can_take_care VALUES ('driddifordjd', 'small dog');
INSERT INTO can_take_care VALUES ('cmurrellje', 'small dog');
INSERT INTO can_take_care VALUES ('jortsjf', 'rabbit');
INSERT INTO can_take_care VALUES ('eboddjg', 'small dog');
INSERT INTO can_take_care VALUES ('cmccawleyjh', 'small dog');
INSERT INTO can_take_care VALUES ('acurrallji', 'big dog');
INSERT INTO can_take_care VALUES ('kdowntonjj', 'small dog');
INSERT INTO can_take_care VALUES ('fcamellijk', 'big dog');
INSERT INTO can_take_care VALUES ('zseabournejl', 'cat');
INSERT INTO can_take_care VALUES ('claffertyjm', 'bird');
INSERT INTO can_take_care VALUES ('csarginsonjn', 'cat');
INSERT INTO can_take_care VALUES ('agarstanjo', 'small dog');
INSERT INTO can_take_care VALUES ('dvedekhovjp', 'rabbit');
INSERT INTO can_take_care VALUES ('agunningjq', 'bird');
INSERT INTO can_take_care VALUES ('ahalvosenjr', 'cat');
INSERT INTO can_take_care VALUES ('caverilljs', 'bird');
INSERT INTO can_take_care VALUES ('acracknelljt', 'big dog');
INSERT INTO can_take_care VALUES ('sugoju', 'rabbit');
INSERT INTO can_take_care VALUES ('spescodjv', 'rodent');
INSERT INTO can_take_care VALUES ('bangeljw', 'small dog');
INSERT INTO can_take_care VALUES ('wjustunjx', 'rabbit');
INSERT INTO can_take_care VALUES ('dgarmstonjy', 'bird');
INSERT INTO can_take_care VALUES ('kwyardjz', 'bird');
INSERT INTO can_take_care VALUES ('zallikerk0', 'big dog');
INSERT INTO can_take_care VALUES ('zlawreyk1', 'cat');
INSERT INTO can_take_care VALUES ('eevamyk2', 'cat');
INSERT INTO can_take_care VALUES ('acolbornk3', 'small dog');
INSERT INTO can_take_care VALUES ('rknowlerk4', 'big dog');
INSERT INTO can_take_care VALUES ('hlorenzink5', 'rabbit');
INSERT INTO can_take_care VALUES ('sfollitk6', 'bird');
INSERT INTO can_take_care VALUES ('vwalshawk7', 'rodent');
INSERT INTO can_take_care VALUES ('slamprechtk8', 'rabbit');
INSERT INTO can_take_care VALUES ('jcursonk9', 'rodent');
INSERT INTO can_take_care VALUES ('hfarndellka', 'rodent');
INSERT INTO can_take_care VALUES ('rspurdenkb', 'rabbit');
INSERT INTO can_take_care VALUES ('dpeerkc', 'small dog');
INSERT INTO can_take_care VALUES ('blekd', 'small dog');
INSERT INTO can_take_care VALUES ('apoggke', 'bird');
INSERT INTO can_take_care VALUES ('lbygrovekf', 'small dog');
INSERT INTO can_take_care VALUES ('kregorzkg', 'small dog');
INSERT INTO can_take_care VALUES ('aaleksahkinkh', 'big dog');
INSERT INTO can_take_care VALUES ('aballingalki', 'cat');
INSERT INTO can_take_care VALUES ('kspottiswoodkj', 'bird');
INSERT INTO can_take_care VALUES ('alenaghenkk', 'rodent');
INSERT INTO can_take_care VALUES ('jstrelitzkl', 'big dog');
INSERT INTO can_take_care VALUES ('kgrenkovkm', 'small dog');
INSERT INTO can_take_care VALUES ('msipsonkn', 'small dog');
INSERT INTO can_take_care VALUES ('buphillko', 'small dog');
INSERT INTO can_take_care VALUES ('cblightkp', 'rodent');
INSERT INTO can_take_care VALUES ('dmatevosiankq', 'small dog');
INSERT INTO can_take_care VALUES ('foscroftkr', 'bird');
INSERT INTO can_take_care VALUES ('tsewellks', 'bird');
INSERT INTO can_take_care VALUES ('aprimmerkt', 'small dog');
INSERT INTO can_take_care VALUES ('plittleoverku', 'big dog');
INSERT INTO can_take_care VALUES ('smordiekv', 'bird');
INSERT INTO can_take_care VALUES ('chanrahankw', 'small dog');
INSERT INTO can_take_care VALUES ('loldamkx', 'cat');
INSERT INTO can_take_care VALUES ('ptobinky', 'big dog');
INSERT INTO can_take_care VALUES ('bebdenkz', 'rodent');
INSERT INTO can_take_care VALUES ('eritzmanl0', 'big dog');
INSERT INTO can_take_care VALUES ('rqueyeirol1', 'big dog');
INSERT INTO can_take_care VALUES ('cnavarrol2', 'small dog');
INSERT INTO can_take_care VALUES ('ngreensmithl3', 'rodent');
INSERT INTO can_take_care VALUES ('hivanishchevl4', 'bird');
INSERT INTO can_take_care VALUES ('erizzillol5', 'cat');
INSERT INTO can_take_care VALUES ('kblaszczykl6', 'bird');
INSERT INTO can_take_care VALUES ('trizzellil7', 'big dog');
INSERT INTO can_take_care VALUES ('icuradol8', 'rodent');
INSERT INTO can_take_care VALUES ('lrapperl9', 'cat');
INSERT INTO can_take_care VALUES ('aandraultla', 'rabbit');
INSERT INTO can_take_care VALUES ('ohimsworthlb', 'small dog');
INSERT INTO can_take_care VALUES ('sbickerstasselc', 'small dog');
INSERT INTO can_take_care VALUES ('jfairbrassld', 'small dog');
INSERT INTO can_take_care VALUES ('cgrissettle', 'cat');
INSERT INTO can_take_care VALUES ('akitchenlf', 'rabbit');
INSERT INTO can_take_care VALUES ('apapaminaslg', 'big dog');
INSERT INTO can_take_care VALUES ('bellerylh', 'big dog');
INSERT INTO can_take_care VALUES ('fpartletonli', 'rodent');
INSERT INTO can_take_care VALUES ('kgisburnelj', 'cat');
INSERT INTO can_take_care VALUES ('mrufflelk', 'rodent');
INSERT INTO can_take_care VALUES ('pcolesll', 'small dog');
INSERT INTO can_take_care VALUES ('kbydawaylm', 'rabbit');
INSERT INTO can_take_care VALUES ('lmontesln', 'bird');
INSERT INTO can_take_care VALUES ('qmaltmanlo', 'cat');
INSERT INTO can_take_care VALUES ('jnannizzilp', 'cat');
INSERT INTO can_take_care VALUES ('nvarcoelq', 'big dog');
INSERT INTO can_take_care VALUES ('scurlesslr', 'rabbit');
INSERT INTO can_take_care VALUES ('shazlehurstls', 'bird');
INSERT INTO can_take_care VALUES ('vcanlandlt', 'rabbit');
INSERT INTO can_take_care VALUES ('lmoremanlu', 'bird');
INSERT INTO can_take_care VALUES ('ltummondlv', 'bird');
INSERT INTO can_take_care VALUES ('flowdeanelw', 'rabbit');
INSERT INTO can_take_care VALUES ('jblennerhassettlx', 'bird');
INSERT INTO can_take_care VALUES ('fstammirsly', 'bird');
INSERT INTO can_take_care VALUES ('omarconilz', 'big dog');
INSERT INTO can_take_care VALUES ('mbeechenom0', 'bird');
INSERT INTO can_take_care VALUES ('tmapesm1', 'bird');
INSERT INTO can_take_care VALUES ('lgoudiem2', 'rodent');
INSERT INTO can_take_care VALUES ('hpasseym3', 'bird');
INSERT INTO can_take_care VALUES ('fbreitlingm4', 'big dog');
INSERT INTO can_take_care VALUES ('ahinzm5', 'cat');
INSERT INTO can_take_care VALUES ('rspatarim6', 'big dog');
INSERT INTO can_take_care VALUES ('paireym7', 'rodent');
INSERT INTO can_take_care VALUES ('htitcombem8', 'cat');
INSERT INTO can_take_care VALUES ('mmaddernm9', 'bird');
INSERT INTO can_take_care VALUES ('pjovasevicma', 'small dog');
INSERT INTO can_take_care VALUES ('rplettsmb', 'small dog');
INSERT INTO can_take_care VALUES ('sblackmanmc', 'rodent');
INSERT INTO can_take_care VALUES ('ftiddymd', 'cat');
INSERT INTO can_take_care VALUES ('bfoggme', 'rabbit');
INSERT INTO can_take_care VALUES ('cshieldsmf', 'big dog');
INSERT INTO can_take_care VALUES ('asacchettimg', 'small dog');
INSERT INTO can_take_care VALUES ('wisleymh', 'small dog');
INSERT INTO can_take_care VALUES ('afernaomi', 'rodent');
INSERT INTO can_take_care VALUES ('callgoodmj', 'bird');
INSERT INTO can_take_care VALUES ('awarnesmk', 'bird');
INSERT INTO can_take_care VALUES ('ghalksworthml', 'rodent');
INSERT INTO can_take_care VALUES ('wlemanumm', 'bird');
INSERT INTO can_take_care VALUES ('mwontnermn', 'bird');
INSERT INTO can_take_care VALUES ('dcongreavemo', 'bird');
INSERT INTO can_take_care VALUES ('ijerromesmp', 'big dog');
INSERT INTO can_take_care VALUES ('ftignermq', 'big dog');
INSERT INTO can_take_care VALUES ('scoggeshallmr', 'small dog');
INSERT INTO can_take_care VALUES ('lhulmesms', 'rabbit');
INSERT INTO can_take_care VALUES ('simmmt', 'small dog');
INSERT INTO can_take_care VALUES ('bclynemu', 'rabbit');
INSERT INTO can_take_care VALUES ('apigfordmv', 'cat');
INSERT INTO can_take_care VALUES ('gwhathammw', 'bird');
INSERT INTO can_take_care VALUES ('bbandemx', 'cat');
INSERT INTO can_take_care VALUES ('rlathleiffuremy', 'bird');
INSERT INTO can_take_care VALUES ('mboulgermz', 'rabbit');
INSERT INTO can_take_care VALUES ('erameyn0', 'cat');
INSERT INTO can_take_care VALUES ('mbrabinn1', 'rodent');
INSERT INTO can_take_care VALUES ('divashechkinn2', 'bird');
INSERT INTO can_take_care VALUES ('mkaliszn3', 'bird');
INSERT INTO can_take_care VALUES ('gburmastern4', 'big dog');
INSERT INTO can_take_care VALUES ('valdersleyn5', 'bird');
INSERT INTO can_take_care VALUES ('smccallumn6', 'small dog');
INSERT INTO can_take_care VALUES ('nravenhillsn7', 'bird');
INSERT INTO can_take_care VALUES ('ebullenn8', 'bird');
INSERT INTO can_take_care VALUES ('fpottagen9', 'rabbit');
INSERT INTO can_take_care VALUES ('glunckna', 'bird');
INSERT INTO can_take_care VALUES ('lhunnisettnb', 'small dog');
INSERT INTO can_take_care VALUES ('jtombsnc', 'cat');
INSERT INTO can_take_care VALUES ('rreburnnd', 'rodent');
INSERT INTO can_take_care VALUES ('mlentonne', 'rabbit');
INSERT INTO can_take_care VALUES ('morringenf', 'cat');
INSERT INTO can_take_care VALUES ('mpollng', 'rabbit');
INSERT INTO can_take_care VALUES ('gdorsaynh', 'rodent');
INSERT INTO can_take_care VALUES ('aitzkovwichni', 'bird');
INSERT INTO can_take_care VALUES ('eburbridgenj', 'big dog');
INSERT INTO can_take_care VALUES ('jgirodnk', 'bird');
INSERT INTO can_take_care VALUES ('acursonnl', 'big dog');
INSERT INTO can_take_care VALUES ('asouthnm', 'rabbit');
INSERT INTO can_take_care VALUES ('zmarchellinn', 'big dog');
INSERT INTO can_take_care VALUES ('csawfordno', 'big dog');
INSERT INTO can_take_care VALUES ('dwapplenp', 'rodent');
INSERT INTO can_take_care VALUES ('asanznq', 'rodent');
INSERT INTO can_take_care VALUES ('mlearmonthnr', 'rabbit');
INSERT INTO can_take_care VALUES ('llivettns', 'big dog');
INSERT INTO can_take_care VALUES ('ceccersleynt', 'big dog');
INSERT INTO can_take_care VALUES ('mfostonnu', 'rodent');
INSERT INTO can_take_care VALUES ('lsarvernv', 'small dog');
INSERT INTO can_take_care VALUES ('sbodemeaidnw', 'bird');
INSERT INTO can_take_care VALUES ('sborrownx', 'bird');
INSERT INTO can_take_care VALUES ('ibeadlesny', 'rabbit');
INSERT INTO can_take_care VALUES ('rdundendalenz', 'rodent');
INSERT INTO can_take_care VALUES ('tmcwaterso0', 'bird');
INSERT INTO can_take_care VALUES ('ctripeo1', 'rodent');
INSERT INTO can_take_care VALUES ('bvannuccinio2', 'rabbit');
INSERT INTO can_take_care VALUES ('cripshero3', 'rodent');
INSERT INTO can_take_care VALUES ('tpalatinio4', 'big dog');
INSERT INTO can_take_care VALUES ('ppopescuo5', 'big dog');
INSERT INTO can_take_care VALUES ('cpinhorno6', 'small dog');
INSERT INTO can_take_care VALUES ('kradborno7', 'cat');
INSERT INTO can_take_care VALUES ('rveyseyo8', 'big dog');
INSERT INTO can_take_care VALUES ('rwarloweo9', 'cat');
INSERT INTO can_take_care VALUES ('bkelwickoa', 'cat');
INSERT INTO can_take_care VALUES ('mmcveightyob', 'big dog');
INSERT INTO can_take_care VALUES ('ugrangieroc', 'big dog');
INSERT INTO can_take_care VALUES ('vmandresod', 'small dog');
INSERT INTO can_take_care VALUES ('easeyoe', 'small dog');
INSERT INTO can_take_care VALUES ('krisebrowof', 'rodent');
INSERT INTO can_take_care VALUES ('dlabrowog', 'rabbit');
INSERT INTO can_take_care VALUES ('gallettoh', 'small dog');
INSERT INTO can_take_care VALUES ('salliottoi', 'cat');
INSERT INTO can_take_care VALUES ('kgwillimoj', 'big dog');
INSERT INTO can_take_care VALUES ('rtunnahok', 'rabbit');
INSERT INTO can_take_care VALUES ('nnapolitanool', 'big dog');
INSERT INTO can_take_care VALUES ('agatehouseom', 'bird');
INSERT INTO can_take_care VALUES ('skitcatton', 'cat');
INSERT INTO can_take_care VALUES ('pschielloo', 'rodent');
INSERT INTO can_take_care VALUES ('talejoop', 'small dog');
INSERT INTO can_take_care VALUES ('mhammertonoq', 'big dog');
INSERT INTO can_take_care VALUES ('brenzoor', 'rodent');
INSERT INTO can_take_care VALUES ('fmeakinos', 'rabbit');
INSERT INTO can_take_care VALUES ('dhaberchamot', 'rabbit');
INSERT INTO can_take_care VALUES ('mfaneou', 'bird');
INSERT INTO can_take_care VALUES ('jbevilleov', 'bird');
INSERT INTO can_take_care VALUES ('rdallowayow', 'rodent');
INSERT INTO can_take_care VALUES ('jmourantox', 'small dog');
INSERT INTO can_take_care VALUES ('odeyeoy', 'big dog');
INSERT INTO can_take_care VALUES ('fgeddisoz', 'cat');
INSERT INTO can_take_care VALUES ('svineyp0', 'big dog');
INSERT INTO can_take_care VALUES ('renstonp1', 'rabbit');
INSERT INTO can_take_care VALUES ('gcoalep2', 'bird');
INSERT INTO can_take_care VALUES ('snelsenp3', 'small dog');
INSERT INTO can_take_care VALUES ('abalmap4', 'rodent');
INSERT INTO can_take_care VALUES ('jmansfordp5', 'rodent');
INSERT INTO can_take_care VALUES ('bwedlakep6', 'cat');
INSERT INTO can_take_care VALUES ('bdikp7', 'small dog');
INSERT INTO can_take_care VALUES ('kmcevonp8', 'rabbit');
INSERT INTO can_take_care VALUES ('smcmeekanp9', 'bird');
INSERT INTO can_take_care VALUES ('danderspa', 'rodent');
INSERT INTO can_take_care VALUES ('ovescovinipb', 'big dog');
INSERT INTO can_take_care VALUES ('nkabischpc', 'big dog');
INSERT INTO can_take_care VALUES ('zaldridgepd', 'small dog');
INSERT INTO can_take_care VALUES ('ngutridgepe', 'rabbit');
INSERT INTO can_take_care VALUES ('mdumbartonpf', 'rodent');
INSERT INTO can_take_care VALUES ('lfreirepg', 'big dog');
INSERT INTO can_take_care VALUES ('dizkoviczph', 'small dog');
INSERT INTO can_take_care VALUES ('cschankelborgpi', 'rabbit');
INSERT INTO can_take_care VALUES ('rcawkillpj', 'rodent');
INSERT INTO can_take_care VALUES ('adadamopk', 'big dog');
INSERT INTO can_take_care VALUES ('aarnasonpl', 'big dog');
INSERT INTO can_take_care VALUES ('fhansiepm', 'bird');
INSERT INTO can_take_care VALUES ('adiwellpn', 'big dog');
INSERT INTO can_take_care VALUES ('vbottomorepo', 'rabbit');
INSERT INTO can_take_care VALUES ('gcosanspp', 'rodent');
INSERT INTO can_take_care VALUES ('jjaunceypq', 'bird');
INSERT INTO can_take_care VALUES ('belcockspr', 'rodent');
INSERT INTO can_take_care VALUES ('kaldhousps', 'rabbit');
INSERT INTO can_take_care VALUES ('mcabanpt', 'cat');
INSERT INTO can_take_care VALUES ('npoynterpu', 'rabbit');
INSERT INTO can_take_care VALUES ('jmatchittpv', 'small dog');
INSERT INTO can_take_care VALUES ('ofaggepw', 'bird');
INSERT INTO can_take_care VALUES ('hfleypx', 'small dog');
INSERT INTO can_take_care VALUES ('asangerpy', 'big dog');
INSERT INTO can_take_care VALUES ('mclimsonpz', 'rodent');
INSERT INTO can_take_care VALUES ('bcoathupq0', 'cat');
INSERT INTO can_take_care VALUES ('bklimesq1', 'big dog');
INSERT INTO can_take_care VALUES ('tdreesq2', 'bird');
INSERT INTO can_take_care VALUES ('wverityq3', 'cat');
INSERT INTO can_take_care VALUES ('mboscottq4', 'small dog');
INSERT INTO can_take_care VALUES ('jdenchq5', 'small dog');
INSERT INTO can_take_care VALUES ('jwisemanq6', 'rabbit');
INSERT INTO can_take_care VALUES ('claphamq7', 'big dog');
INSERT INTO can_take_care VALUES ('laggsq8', 'big dog');
INSERT INTO can_take_care VALUES ('bfrewerq9', 'rabbit');
INSERT INTO can_take_care VALUES ('mprozesckyqa', 'rodent');
INSERT INTO can_take_care VALUES ('ebourbonqb', 'rabbit');
INSERT INTO can_take_care VALUES ('lizakovitzqc', 'cat');
INSERT INTO can_take_care VALUES ('alamersqd', 'rabbit');
INSERT INTO can_take_care VALUES ('cmarksonqe', 'small dog');
INSERT INTO can_take_care VALUES ('sstanettqf', 'small dog');
INSERT INTO can_take_care VALUES ('bbrittianqg', 'rodent');
INSERT INTO can_take_care VALUES ('afallowqh', 'big dog');
INSERT INTO can_take_care VALUES ('jfouldesqi', 'rodent');
INSERT INTO can_take_care VALUES ('bjimeqj', 'bird');
INSERT INTO can_take_care VALUES ('oangoveqk', 'big dog');
INSERT INTO can_take_care VALUES ('wpantinql', 'cat');
INSERT INTO can_take_care VALUES ('faucoateqm', 'small dog');
INSERT INTO can_take_care VALUES ('mpresshaughqn', 'rodent');
INSERT INTO can_take_care VALUES ('gheindrickqo', 'bird');
INSERT INTO can_take_care VALUES ('lminsterqp', 'rodent');
INSERT INTO can_take_care VALUES ('icurdqq', 'rodent');
INSERT INTO can_take_care VALUES ('mdumbreckqr', 'small dog');
INSERT INTO can_take_care VALUES ('mmetterickqs', 'bird');
INSERT INTO can_take_care VALUES ('ntemperleyqt', 'cat');
INSERT INTO can_take_care VALUES ('wmalickiqu', 'bird');
INSERT INTO can_take_care VALUES ('pdumelowqv', 'bird');
INSERT INTO can_take_care VALUES ('bbottermanqw', 'rodent');
INSERT INTO can_take_care VALUES ('inicelyqx', 'big dog');
INSERT INTO can_take_care VALUES ('fperroniqy', 'big dog');
INSERT INTO can_take_care VALUES ('ssellekqz', 'big dog');
INSERT INTO can_take_care VALUES ('vcrispr0', 'cat');
INSERT INTO can_take_care VALUES ('rcawkerr1', 'rodent');
INSERT INTO can_take_care VALUES ('leshelbyr2', 'rodent');
INSERT INTO can_take_care VALUES ('rwillowbyr3', 'cat');
INSERT INTO can_take_care VALUES ('amacerr4', 'rodent');
INSERT INTO can_take_care VALUES ('bmacsharryr5', 'rodent');
INSERT INTO can_take_care VALUES ('jchamleyr6', 'small dog');
INSERT INTO can_take_care VALUES ('iliasr7', 'bird');
INSERT INTO can_take_care VALUES ('hdanilovr8', 'bird');
INSERT INTO can_take_care VALUES ('ghartoppr9', 'small dog');
INSERT INTO can_take_care VALUES ('bpairemanra', 'small dog');
INSERT INTO can_take_care VALUES ('abenninckrb', 'big dog');
INSERT INTO can_take_care VALUES ('srawlesrc', 'cat');
INSERT INTO can_take_care VALUES ('bbiaggionird', 'big dog');
INSERT INTO can_take_care VALUES ('yfouxre', 'cat');
INSERT INTO can_take_care VALUES ('wmottenrf', 'bird');
INSERT INTO can_take_care VALUES ('sstedsonrg', 'rabbit');
INSERT INTO can_take_care VALUES ('cwiferh', 'rodent');
INSERT INTO can_take_care VALUES ('sospellisseyri', 'small dog');
INSERT INTO can_take_care VALUES ('scumingrj', 'rabbit');
INSERT INTO can_take_care VALUES ('mbovisrk', 'small dog');
INSERT INTO can_take_care VALUES ('iruusarl', 'small dog');
INSERT INTO can_take_care VALUES ('ptoynerm', 'small dog');
INSERT INTO can_take_care VALUES ('khendinrn', 'small dog');
INSERT INTO can_take_care VALUES ('kmelpussro', 'big dog');
INSERT INTO can_take_care VALUES ('tbaversorrp', 'big dog');
INSERT INTO can_take_care VALUES ('lgullisrq', 'rabbit');
INSERT INTO can_take_care VALUES ('ldumbarrr', 'big dog');
INSERT INTO can_take_care VALUES ('dledram0', 'big dog');
INSERT INTO can_take_care VALUES ('pcanceller1', 'rodent');
INSERT INTO can_take_care VALUES ('fdishmon2', 'rodent');
INSERT INTO can_take_care VALUES ('chayton3', 'bird');
INSERT INTO can_take_care VALUES ('tpetch4', 'bird');
INSERT INTO can_take_care VALUES ('bshotton5', 'bird');
INSERT INTO can_take_care VALUES ('fburrus6', 'small dog');
INSERT INTO can_take_care VALUES ('cscarce7', 'rabbit');
INSERT INTO can_take_care VALUES ('awebsdale8', 'big dog');
INSERT INTO can_take_care VALUES ('ejillett9', 'rodent');
INSERT INTO can_take_care VALUES ('jmatyasheva', 'rodent');
INSERT INTO can_take_care VALUES ('afaldoeb', 'rabbit');
INSERT INTO can_take_care VALUES ('mwillgressc', 'rodent');
INSERT INTO can_take_care VALUES ('groubyd', 'small dog');
INSERT INTO can_take_care VALUES ('rbasterfielde', 'cat');
INSERT INTO can_take_care VALUES ('bdengef', 'rabbit');
INSERT INTO can_take_care VALUES ('rsaleg', 'rabbit');
INSERT INTO can_take_care VALUES ('nrozanskih', 'bird');
INSERT INTO can_take_care VALUES ('mpyffei', 'bird');
INSERT INTO can_take_care VALUES ('khamelj', 'rodent');
INSERT INTO can_take_care VALUES ('eesselk', 'rodent');
INSERT INTO can_take_care VALUES ('kfollandl', 'big dog');
INSERT INTO can_take_care VALUES ('rmassimom', 'small dog');
INSERT INTO can_take_care VALUES ('grudwelln', 'cat');
INSERT INTO can_take_care VALUES ('csterryo', 'cat');
INSERT INTO can_take_care VALUES ('fmcclintonp', 'rodent');
INSERT INTO can_take_care VALUES ('cstetlyeq', 'small dog');
INSERT INTO can_take_care VALUES ('jsouthgater', 'rabbit');
INSERT INTO can_take_care VALUES ('cpitrellis', 'small dog');
INSERT INTO can_take_care VALUES ('brisbrought', 'big dog');
INSERT INTO can_take_care VALUES ('cpeinkeu', 'big dog');
INSERT INTO can_take_care VALUES ('nhopewellv', 'big dog');
INSERT INTO can_take_care VALUES ('pyukhnevichw', 'rabbit');
INSERT INTO can_take_care VALUES ('limpeyx', 'cat');
INSERT INTO can_take_care VALUES ('dmaddrelly', 'cat');
INSERT INTO can_take_care VALUES ('wjanczykz', 'rabbit');
INSERT INTO can_take_care VALUES ('aderycot10', 'rodent');
INSERT INTO can_take_care VALUES ('eblofield11', 'rabbit');
INSERT INTO can_take_care VALUES ('gzeplin12', 'bird');
INSERT INTO can_take_care VALUES ('jsambidge13', 'rabbit');
INSERT INTO can_take_care VALUES ('bskamell14', 'cat');
INSERT INTO can_take_care VALUES ('rfeehan15', 'bird');
INSERT INTO can_take_care VALUES ('jgilffilland16', 'cat');
INSERT INTO can_take_care VALUES ('ibandiera17', 'rabbit');
INSERT INTO can_take_care VALUES ('bspittle18', 'bird');
INSERT INTO can_take_care VALUES ('wneill19', 'bird');
INSERT INTO can_take_care VALUES ('egregorin1a', 'rodent');
INSERT INTO can_take_care VALUES ('nlathbury1b', 'small dog');
INSERT INTO can_take_care VALUES ('wpeoples1c', 'big dog');
INSERT INTO can_take_care VALUES ('kfearnyough1d', 'bird');
INSERT INTO can_take_care VALUES ('lsterte1e', 'bird');
INSERT INTO can_take_care VALUES ('fstormonth1f', 'cat');
INSERT INTO can_take_care VALUES ('kmccaughran1g', 'small dog');
INSERT INTO can_take_care VALUES ('cannear1h', 'bird');
INSERT INTO can_take_care VALUES ('gbrennon1i', 'rodent');
INSERT INTO can_take_care VALUES ('nhasker1j', 'cat');
INSERT INTO can_take_care VALUES ('nallsworth1k', 'bird');
INSERT INTO can_take_care VALUES ('rdewdney1l', 'big dog');
INSERT INTO can_take_care VALUES ('hmcgrorty1m', 'cat');
INSERT INTO can_take_care VALUES ('mdinsale1n', 'big dog');
INSERT INTO can_take_care VALUES ('apolson1o', 'bird');
INSERT INTO can_take_care VALUES ('abryden1p', 'rabbit');
INSERT INTO can_take_care VALUES ('rhuzzey1q', 'cat');
INSERT INTO can_take_care VALUES ('aeasseby1r', 'bird');
INSERT INTO can_take_care VALUES ('lbadrick1s', 'rabbit');
INSERT INTO can_take_care VALUES ('dfaivre1t', 'bird');
INSERT INTO can_take_care VALUES ('bwilcox1u', 'small dog');
INSERT INTO can_take_care VALUES ('trennison1v', 'rabbit');
INSERT INTO can_take_care VALUES ('apauley1w', 'cat');
INSERT INTO can_take_care VALUES ('hpancoust1x', 'big dog');
INSERT INTO can_take_care VALUES ('jherley1y', 'bird');
INSERT INTO can_take_care VALUES ('dyarnall1z', 'cat');
INSERT INTO can_take_care VALUES ('ucanizares20', 'small dog');
INSERT INTO can_take_care VALUES ('lskamell21', 'small dog');
INSERT INTO can_take_care VALUES ('ashury22', 'rabbit');
INSERT INTO can_take_care VALUES ('ahuddleston23', 'rodent');
INSERT INTO can_take_care VALUES ('hbecconsall24', 'bird');
INSERT INTO can_take_care VALUES ('sedger25', 'big dog');
INSERT INTO can_take_care VALUES ('emcgrail26', 'cat');
INSERT INTO can_take_care VALUES ('cstriker27', 'bird');
INSERT INTO can_take_care VALUES ('stalboy28', 'small dog');
INSERT INTO can_take_care VALUES ('pbalmforth29', 'big dog');
INSERT INTO can_take_care VALUES ('sspalding2a', 'rodent');
INSERT INTO can_take_care VALUES ('umelanaphy2b', 'rabbit');
INSERT INTO can_take_care VALUES ('aevert2c', 'rodent');
INSERT INTO can_take_care VALUES ('aarnowitz2d', 'rodent');
INSERT INTO can_take_care VALUES ('mfilyaev2e', 'small dog');
INSERT INTO can_take_care VALUES ('ilafoy2f', 'bird');
INSERT INTO can_take_care VALUES ('nbrightling2g', 'rodent');
INSERT INTO can_take_care VALUES ('mlalley2h', 'rodent');
INSERT INTO can_take_care VALUES ('msarjent2i', 'big dog');
INSERT INTO can_take_care VALUES ('gghiron2j', 'big dog');
INSERT INTO can_take_care VALUES ('fcrumly2k', 'rodent');
INSERT INTO can_take_care VALUES ('khusselbee2l', 'small dog');
INSERT INTO can_take_care VALUES ('mgrigorushkin2m', 'bird');
INSERT INTO can_take_care VALUES ('cpiccard2n', 'bird');
INSERT INTO can_take_care VALUES ('gpenhallurick2o', 'small dog');
INSERT INTO can_take_care VALUES ('dsweett2p', 'small dog');
INSERT INTO can_take_care VALUES ('mvoce2q', 'cat');
INSERT INTO can_take_care VALUES ('bjost2r', 'rabbit');
INSERT INTO can_take_care VALUES ('lmcnirlin2s', 'big dog');
INSERT INTO can_take_care VALUES ('sabbot2t', 'big dog');
INSERT INTO can_take_care VALUES ('hluipold2u', 'rabbit');
INSERT INTO can_take_care VALUES ('efarnorth2v', 'cat');
INSERT INTO can_take_care VALUES ('vthalmann2w', 'rabbit');
INSERT INTO can_take_care VALUES ('graithmill2x', 'cat');
INSERT INTO can_take_care VALUES ('sholdron2y', 'bird');
INSERT INTO can_take_care VALUES ('mlangham2z', 'cat');
INSERT INTO can_take_care VALUES ('maslet30', 'rodent');
INSERT INTO can_take_care VALUES ('gyesenev31', 'rodent');
INSERT INTO can_take_care VALUES ('agrantham32', 'rabbit');
INSERT INTO can_take_care VALUES ('khupe33', 'rabbit');
INSERT INTO can_take_care VALUES ('rhelm34', 'small dog');
INSERT INTO can_take_care VALUES ('sjoyson35', 'bird');
INSERT INTO can_take_care VALUES ('lnesbeth36', 'rabbit');
INSERT INTO can_take_care VALUES ('hbortolotti37', 'small dog');
INSERT INTO can_take_care VALUES ('ncarr38', 'rabbit');
INSERT INTO can_take_care VALUES ('tmcevilly39', 'rodent');
INSERT INTO can_take_care VALUES ('yollarenshaw3a', 'rabbit');
INSERT INTO can_take_care VALUES ('adundin3b', 'rodent');
INSERT INTO can_take_care VALUES ('kbrand3c', 'cat');
INSERT INTO can_take_care VALUES ('svasiliev3d', 'big dog');
INSERT INTO can_take_care VALUES ('letteridge3e', 'cat');
INSERT INTO can_take_care VALUES ('tminshull3f', 'rodent');
INSERT INTO can_take_care VALUES ('rjedrysik3g', 'small dog');
INSERT INTO can_take_care VALUES ('cweyman3h', 'rodent');
INSERT INTO can_take_care VALUES ('mvasilyevski3i', 'big dog');
INSERT INTO can_take_care VALUES ('jsilverthorn3j', 'small dog');
INSERT INTO can_take_care VALUES ('kgeane3k', 'cat');
INSERT INTO can_take_care VALUES ('bsibly3l', 'rabbit');
INSERT INTO can_take_care VALUES ('tfereday3m', 'big dog');
INSERT INTO can_take_care VALUES ('fgallamore3n', 'rodent');
INSERT INTO can_take_care VALUES ('tolford3o', 'cat');
INSERT INTO can_take_care VALUES ('scurrey3p', 'small dog');
INSERT INTO can_take_care VALUES ('dorange3q', 'rabbit');
INSERT INTO can_take_care VALUES ('owoodsford3r', 'rodent');
INSERT INTO can_take_care VALUES ('jmccrisken3s', 'rabbit');
INSERT INTO can_take_care VALUES ('okleszinski3t', 'bird');
INSERT INTO can_take_care VALUES ('mpardie3u', 'big dog');
INSERT INTO can_take_care VALUES ('erouch3v', 'cat');
INSERT INTO can_take_care VALUES ('bsingleton3w', 'rabbit');
INSERT INTO can_take_care VALUES ('nmcclenaghan3x', 'rodent');
INSERT INTO can_take_care VALUES ('adyos3y', 'small dog');
INSERT INTO can_take_care VALUES ('eburehill3z', 'rabbit');
INSERT INTO can_take_care VALUES ('jnott40', 'bird');
INSERT INTO can_take_care VALUES ('elorenzetti41', 'rabbit');
INSERT INTO can_take_care VALUES ('flewinton42', 'big dog');
INSERT INTO can_take_care VALUES ('jrushmer43', 'bird');
INSERT INTO can_take_care VALUES ('epaulet44', 'small dog');
INSERT INTO can_take_care VALUES ('gdillingham45', 'rabbit');
INSERT INTO can_take_care VALUES ('mboichat46', 'small dog');
INSERT INTO can_take_care VALUES ('rfoston47', 'rabbit');
INSERT INTO can_take_care VALUES ('mmccullen48', 'small dog');
INSERT INTO can_take_care VALUES ('gswadlinge49', 'rabbit');
INSERT INTO can_take_care VALUES ('rsargood4a', 'big dog');
INSERT INTO can_take_care VALUES ('iwadman4b', 'cat');
INSERT INTO can_take_care VALUES ('tbitcheno4c', 'rabbit');
INSERT INTO can_take_care VALUES ('ccawsby4d', 'rodent');
INSERT INTO can_take_care VALUES ('zrazzell4e', 'bird');
INSERT INTO can_take_care VALUES ('dgorham4f', 'small dog');
INSERT INTO can_take_care VALUES ('jjahndel4g', 'rodent');
INSERT INTO can_take_care VALUES ('abricksey4h', 'bird');
INSERT INTO can_take_care VALUES ('ncraig4i', 'big dog');
INSERT INTO can_take_care VALUES ('rwestcot4j', 'rabbit');
INSERT INTO can_take_care VALUES ('jnuth4k', 'big dog');
INSERT INTO can_take_care VALUES ('achurcher4l', 'small dog');
INSERT INTO can_take_care VALUES ('vbolus4m', 'rabbit');
INSERT INTO can_take_care VALUES ('gwroath4n', 'rodent');
INSERT INTO can_take_care VALUES ('bbeaufoy4o', 'cat');
INSERT INTO can_take_care VALUES ('bolligan4p', 'rabbit');
INSERT INTO can_take_care VALUES ('mstiegars4q', 'rodent');
INSERT INTO can_take_care VALUES ('rolohan4r', 'rabbit');
INSERT INTO can_take_care VALUES ('mdorrington4s', 'cat');
INSERT INTO can_take_care VALUES ('pwhyke4t', 'cat');
INSERT INTO can_take_care VALUES ('rgiuron4u', 'cat');
INSERT INTO can_take_care VALUES ('spool4v', 'cat');
INSERT INTO can_take_care VALUES ('igapper4w', 'rabbit');
INSERT INTO can_take_care VALUES ('crust4x', 'big dog');
INSERT INTO can_take_care VALUES ('awollard4y', 'small dog');
INSERT INTO can_take_care VALUES ('rberntsson4z', 'rabbit');
INSERT INTO can_take_care VALUES ('jbarwick50', 'rodent');
INSERT INTO can_take_care VALUES ('htruman51', 'big dog');
INSERT INTO can_take_care VALUES ('rclapison52', 'rabbit');
INSERT INTO can_take_care VALUES ('kcarlan53', 'rodent');
INSERT INTO can_take_care VALUES ('bmassenhove54', 'small dog');
INSERT INTO can_take_care VALUES ('psoff55', 'rabbit');
INSERT INTO can_take_care VALUES ('aprendeville56', 'rabbit');
INSERT INTO can_take_care VALUES ('adovington57', 'rabbit');
INSERT INTO can_take_care VALUES ('jhowse58', 'cat');
INSERT INTO can_take_care VALUES ('jpopelay59', 'big dog');
INSERT INTO can_take_care VALUES ('otrevaskiss5a', 'bird');
INSERT INTO can_take_care VALUES ('baveyard5b', 'small dog');
INSERT INTO can_take_care VALUES ('ccunde5c', 'bird');
INSERT INTO can_take_care VALUES ('jpaddefield5d', 'big dog');
INSERT INTO can_take_care VALUES ('wgallon5e', 'cat');
INSERT INTO can_take_care VALUES ('bpolotti5f', 'big dog');
INSERT INTO can_take_care VALUES ('maubury5g', 'big dog');
INSERT INTO can_take_care VALUES ('crowles5h', 'cat');
INSERT INTO can_take_care VALUES ('amacrury5i', 'rodent');
INSERT INTO can_take_care VALUES ('iohanlon5j', 'big dog');
